### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by MisterAlex95** [xerpi/vita2dlib#19]
Hello!
Thanks for your lib !

I didn't find any fonctions to get color of one pixel. Am I stupid or it's true ? :)

Thanks !

**Comment by xerpi** [comment]
Do you want to get the pixel from the texture or the framebuffer?

**Comment by MisterAlex95** [comment]
Framebuffer will be perfect :)

**Comment by xerpi** [comment]
You can do something like:

``` c
unsigned int get_pixel(int x, int y)
{
    unsigned int *buffer = vita2d_get_current_fb();
    return buffer[x + y * 544];
}

But be careful when you call vita2d_get_current_fb(), the GPU may still be writing to the framebuffer when you try to read from it.
```

**Comment by MisterAlex95** [comment]
Thank a lot !

**Comment by ljkgpxs** [comment]
Why not add a new function vita2d_draw_texture_part_scale_rotate_hotspot ;)
