### ISSUE TITLE
Adding sharp bilinear shader?

### ISSUE THREAD

**Issue by rsn8887** [xerpi/vita2dlib#38]
I am interested in adding the sharpbilinear.cg shader from here 
https://github.com/libretro/common-shaders/blob/master/retro/shaders/sharp-bilinear.cg .

That's upscaling small textures to 2x the original resolution with point filtering and then bilinear filter to whatever size is in the viewport.

This would give nice sharp 2D graphics without pixel wobble and minimal blur even at non-integer scaling factors, useful for emulators and 2D games. I am interested in it for uae4all2, where the texture is 320*240.

But how can I add a shader? I added the obvious 1,000 functions here, mimicking the tint shader program directives: https://github.com/rsn8887/libvita2d/commit/4917ac970040898f4ad8eaaf3076bb9f59708e24

However, now I am stuck because my new variable
extern const SceGxmProgram texture_sharpbilinear_f_gxp_start
is not defined anywhere?

I suppose I have to tell the program the hex offset where my shader starts, but I have no clue how.

**Comment by xerpi** [comment]
You need to compile your shader (ask me privately on IRC if you want to know how) and just link it with the rest of shaders and object files.

**Comment by rsn8887** [comment]
This has been done a long time ago in FrangarCJ’s shader Collection and vita2d gtu branch.
