### ISSUE TITLE
open an not exist jpg file using function "vita2d_load_JPEG_file" , and program crash. 

### ISSUE THREAD

**Issue by jokewayne** [xerpi/vita2dlib#64]
Hi xerpi, 
    first of all thanks for your libvita2d, I couldn't have done my own program without it.
    
    I encounter a crash when I accidently try to open an not exist jpg file.
    I try to locate it, and found that the function "vita2d_load_JPEG_file" in "vita2d_image_jpeg.c" file.
using the following code:
if ((fp = fopen(filename, "rb")) < 0) {
		return NULL;
	}
    I test it.  When fopen failed, fp is 0, so it will not return NULL. 
And I change "<" into "<=" , like below:
if ((fp = fopen(filename, "rb")) <= 0) {
		return NULL;
	} 

the program seems not crash any more.
So I guess that is where the problem is.

**Comment by xerpi** [comment]
That's right! Mind sending a pull request?

**Comment by jokewayne** [comment]
I just did.
 : )
