### ISSUE TITLE
Load Texture Limited ??

### ISSUE THREAD

**Issue by BenMitnicK** [xerpi/vita2dlib#66]
I Have a problem with my 2 apps and the same problem. I can't load texture more than 16 images in my array texture but with the debug All name is fine. Ma question is ... Vita2d is limited in memory for loading image file in the array texture ?? 

1) Here the sample code 
 https://pastebin.com/fqHfwXEA

2) Here the debug of my book apps with the same issue over 16 images no texture loaded I have the same problem with the jpeg or the bmp and mixing them it's the same
https://pastebin.com/j8bFBSxS

**Comment by BenMitnicK** [comment]
I load juste 20 images and over 16 (Bad Load)
I rewrite the code no matter what I do it's always the same

**Comment by xerpi** [comment]
Have you tried loading less images? Btw what's the dimensions of each image?

**Comment by BenMitnicK** [comment]
yes under 16 no problem, 16 perfect and above bad load, 16 images loaded correctly from 17/20/50/100 images just 16 is loaded no more

PSVita dimensions 960x544 I use images from the vita game (Manual) for my test 

[Images Pack](https://ufile.io/30hzp)

**Comment by xerpi** [comment]
Keep in mind a single 960x544 image takes `960 * 544 * 4 = 2MiB` of memory, so it's very likely that you are running out of memory.

**Comment by BenMitnicK** [comment]
I just tested other images below 960x544 and also a mix between small images and images in 960x544 I can load more than 16 images but still limited. it's unfortunate to be limited because if I do images per image navigation and too slow the user can not advance quickly to the 20th image for example that's why I wanted to store them in an array for navigation quick. I will have to do image by image which is not great to read a book otherwise find another solution. Thank you for your help and all your answers

**Comment by xerpi** [comment]
You could try saving the previous 5 and next 5 iterations and load/unload on demand on a secondary thread.
Having 10s of 960*544 images loaded at the same time is not a good idea.

**Comment by BenMitnicK** [comment]
yes my friend I just understand the operation of all that and I had the same idea as you all 10 images but I found another solution that works quite well. I thank you for your help in any case :) you can close the issue

**Comment by xerpi** [comment]
Good to hear!

**Comment by devnoname120** [comment]
For future reference you can increase the available memory by doing [the following](https://github.com/bvschaik/julius/blob/7ecc21b570abba068db788a446bc1dc03e5d5695/src/platform/vita/vita.c#L8-L9):
```C
// max heap size is approx. 330 MB with -d ATTRIBUTE2=12, otherwise max is 192
int _newlib_heap_size_user = 300 * 1024 * 1024;
```
